**Following guidelines set expectations for participant behaviour during workshop activities. They also ensure that the class environment is welcoming, inclusive, and respectful.**
- Where a discussion is taking place, allow everyone a chance to speak
- Listen respectfully, without interrupting and with an open mind to understanding others’ views
- Be professional and productive, and always share your ideas, your opinion matters, we all can learn something from each other
- Personal information that comes up in the conversation should be kept confidential
- Avoid inflammatory language
- Avoid assumptions about any member of the class or generalisations about social groups

**You have now joined a group of fellow analysts in a workshop:**
#### Outcomes:

- To complete a group activity to identify how Data Processing with pandas could be useful for your job role
- To be able to answer the questions to test your knowledge of Data Processing with pandas


#### Note:
- We understand learners will progress at their own speed
- Tutors will be on hand to answer questions

## Group activity

- Identify how **Data Processing with pandas** could be useful for data analytics within your job role? And share your thoughts.

In [1]:
#add your notes below

# Data Processing with `pandas`

## Part 1: Combining datasets

- Make sure you run the following code cell before you attempt any of the questions
- In the following section, you will be analysing some data related to a small coffee shop chain

In [2]:
import pandas as pd

from dataframes import europe, americas, requirements, prices, currencies, exchange_rates, dublin

Here are some details of outlets in a small coffee shop chain:

In [3]:
europe

   location_id  Country       City
0            1       UK  Cambridge
1            2    Italy    Sanremo
2            3   France      Paris
3            4  Germany     Berlin

In [4]:
americas

   location_id    Country           City
0            1  Argentina   Buenos Aires
1            2     Brazil            Rio
2            3        USA       New York
3            4        USA  San Francisco

**Q1)** Concatenate two pandas DataFrames

- For this task use `pd.concat()` function with `ignore_index=True` parameter to combine `europe` and `americas` dataframes, with the `europe` entries first 

- The `location_id` column can be left as it is (we will resolve the duplicate values later)

- Call the new DataFrame `outlets` which should contains eight entries, and has a index with unique values from 0 to 7 

*To find out more about: [pd.concat](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html)

In [5]:
#add your code below

outlets = pd.concat([europe, americas], ignore_index=True)
outlets

   location_id    Country           City
0            1         UK      Cambridge
1            2      Italy        Sanremo
2            3     France          Paris
3            4    Germany         Berlin
4            1  Argentina   Buenos Aires
5            2     Brazil            Rio
6            3        USA       New York
7            4        USA  San Francisco

A new outlet will be opened in Dublin. A site is found, and it has the following `requirements`:

In [6]:
requirements

             name  quantity
0           table        30
1           chair       100
2  coffee machine         2

There’s a catalogue of `prices` as follows:

In [7]:
prices

             name  price
0           table     50
1           chair     20
2  coffee machine   1000

**Q2)** Join two Pandas DataFrames

- For this task use `.merge()` method

- Merge the `requirements` table with `prices` on `name`, creating a new DataFrame called `purchases` which is the same as `requirements` but with a `price` column added, and another column `cost` which is equal to `price` * `quantity`:

*To find out more about: [merge](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html)

In [8]:
#add your code below

purchases = requirements.merge(prices, how="left", on="name")
purchases['cost'] = purchases['price']*purchases['quantity']
purchases

             name  quantity  price  cost
0           table        30     50  1500
1           chair       100     20  2000
2  coffee machine         2   1000  2000

The details for the Dublin branch are in the `dublin` DataFrame:

In [9]:
dublin

  location_id  Country    City
0           5  Ireland  Dublin

**Q3)** Concatenate two pandas DataFrames
- Add `dublin` DataFrame to the bottom of the `outlets` DataFrame using `pd.concat()` function with `ignore_index=True` parameter, again updating the row index so that it has numbers `0` to `8`:
- Save the new DataFrame as `outlets_new`

In [10]:
#add your code below

outlets_new = pd.concat([outlets, dublin], ignore_index=True)
outlets_new

  location_id    Country           City
0           1         UK      Cambridge
1           2      Italy        Sanremo
2           3     France          Paris
3           4    Germany         Berlin
4           1  Argentina   Buenos Aires
5           2     Brazil            Rio
6           3        USA       New York
7           4        USA  San Francisco
8           5    Ireland         Dublin

## Part 2: Data preparation and cleaning

- Make sure you run the following code cell before you attempt any of the questions
- This section is a continuation of the previous analysis activities, here you will be analysing some data related to a small coffee shop chain

`currencies` DataFrame contains the `currency` information for each country in which there is an outlet:

In [11]:
currencies

     country currency
0         UK    Pound
1    Ireland     Euro
2      Italy     Euro
3     France     Euro
4    Germany     Euro
5  Argentina     Peso
6     Brazil     Real
7        USA   Dollar

**Q4)**  Avoid modifying the original `outlets_new` DataFrame. 

- Use `.copy()` method to create a new DataFrame called `outlets_detail`, which is the same as `outlets_new` DataFrame
- Merge `outlets_detail` DataFrame with `currencies` DataFrame to get currency information for each outlet. Notice that in the `currencies` DataFrame, the column heading `country` is lower case so does not quite match with column heading `Country` in `outlets_detail` DataFrame
- Use `.drop()` method with `axis=1` parameter to drop column heading `country`
- Use `.rename` method to rename the column heading `currency` to `Currency`

In [12]:
#add your code below

outlets_detail = outlets_new.copy()


outlets_detail = outlets_detail.merge(currencies, how='left', left_on='Country', right_on='country') 


outlets_detail.drop('country', axis=1, inplace=True)

outlets_detail.rename(columns = {'currency': 'Currency'}, inplace=True)


outlets_detail

  location_id    Country           City Currency
0           1         UK      Cambridge    Pound
1           2      Italy        Sanremo     Euro
2           3     France          Paris     Euro
3           4    Germany         Berlin     Euro
4           1  Argentina   Buenos Aires     Peso
5           2     Brazil            Rio     Real
6           3        USA       New York   Dollar
7           4        USA  San Francisco   Dollar
8           5    Ireland         Dublin     Euro

Run the following code to create lists of the countries where there are outlets in the two regions:

In [13]:
EUROPE = ['UK', 'Italy', 'France', 'Germany', 'Ireland']
AMERICAS = ['Argentina', 'Brazil', 'USA']

You have been given the below code for the function called `region`, which takes a single argument, `country`, and returns **'Europe'** if in `EUROPE` list, **'Americas'** if in `AMERICAS` list, and **'Other'** if in neither list. Make sure you run the following code cell before you attempt any of the questions:

In [14]:
def region(country):
    
    if country in EUROPE:
        return 'Europe'
    elif country in AMERICAS:
        return 'Americas'
    else:
        return 'Other'

**Q5)** Add a new column `Region` to `outlets_detail` DataFrame, which uses the function `region` and `.apply()` method to populate the column values. 

- The new values being generated should be based on the `Country` column in `outlets_detail` DataFrame

In [15]:
#add your code below
outlets_detail['region'] = outlets_detail['Country'].apply(region)
outlets_detail

  location_id    Country           City Currency    region
0           1         UK      Cambridge    Pound    Europe
1           2      Italy        Sanremo     Euro    Europe
2           3     France          Paris     Euro    Europe
3           4    Germany         Berlin     Euro    Europe
4           1  Argentina   Buenos Aires     Peso  Americas
5           2     Brazil            Rio     Real  Americas
6           3        USA       New York   Dollar  Americas
7           4        USA  San Francisco   Dollar  Americas
8           5    Ireland         Dublin     Euro    Europe

You have been given the below code for creating a new column `new_id` which contains strings in the format `<Region>_<location_id>`, for example: `Europe_1`

In [16]:
outlets_detail['new_id'] = outlets_detail['region'] + '_' + outlets_detail['location_id'].astype(str)
outlets_detail

  location_id    Country           City Currency    region      new_id
0           1         UK      Cambridge    Pound    Europe    Europe_1
1           2      Italy        Sanremo     Euro    Europe    Europe_2
2           3     France          Paris     Euro    Europe    Europe_3
3           4    Germany         Berlin     Euro    Europe    Europe_4
4           1  Argentina   Buenos Aires     Peso  Americas  Americas_1
5           2     Brazil            Rio     Real  Americas  Americas_2
6           3        USA       New York   Dollar  Americas  Americas_3
7           4        USA  San Francisco   Dollar  Americas  Americas_4
8           5    Ireland         Dublin     Euro    Europe    Europe_5

**Q6)** Use `.copy()` method to create a new DataFrame called `outlets_final`, which is the same as `outlets_detail` DataFrame.

- On `outlets_final` DataFrame, drop the original `location_id` column, use `.drop()` method with `axis=1` parameter, and set the index of the DataFrame as `new_id` column, discarding the original index:

In [17]:
#add your code below
#outlets_final = outlets_detail.copy()
outlets_final = outlets_detail.copy()
outlets_final.drop('location_id',axis=1,inplace=True)
outlets_final.set_index('new_id',inplace=True)
outlets_final

              Country           City Currency    region
new_id
Europe_1           UK      Cambridge    Pound    Europe
Europe_2        Italy        Sanremo     Euro    Europe
Europe_3       France          Paris     Euro    Europe
Europe_4      Germany         Berlin     Euro    Europe
Americas_1  Argentina   Buenos Aires     Peso  Americas
Americas_2     Brazil            Rio     Real  Americas
Americas_3        USA       New York   Dollar  Americas
Americas_4        USA  San Francisco   Dollar  Americas
Europe_5      Ireland         Dublin     Euro    Europe

*Note how the `.drop()` method is destructive, in that running the code a second time will throw an error because the given column cannot be found. In these circumstances you may need to re-run previous code to get the DataFrame back to its previous state.*

## Part 3: Data grouping and aggregation

- Make sure you run the following code cell before you attempt any of the questions
- In the following section, you will be analysing some data related to ward profiles for each ward in Greater London. This will give an overview of the population in these small areas by presenting a range of data on the population, diversity, households, life expectancy, housing, crime, benefits, land use, deprivation, and employment

*To find out more about the dataset: [link](https://www.data.gov.uk/dataset/c7869dd4-7a05-4d5d-9e42-bdfc8da8c1b7/ward-profiles-and-atlas)

In [18]:
import pandas as pd

In [19]:
wards = pd.read_csv('data/ward-profiles-clean.csv')
wards.head()

,Borough,Ward,Population - 2015,Children aged 0-15 - 2015,Working-age (16-64) - 2015,Older people aged 65+ - 2015,% All Children aged 0-15 - 2015,% All Working-age (16-64) - 2015,% All Older people aged 65+ - 2015,Mean Age - 2013,...,A-Level Average Point Score Per Student - 2013/14,A-Level Average Point Score Per Entry; 2013/14,Crime rate - 2014/15,Violence against the person rate - 2014/15,"Deliberate Fires per 1,000 population - 2014",% area that is open space - 2014,Cars per household - 2011,Average Public Transport Accessibility score - 2014,% travel by bicycle to work - 2011,Turnout at Mayoral election - 2012
0,City of London,City of London,8100,650,6250,1250,8.0,76.9,15.2,41.3,...,662.9,210.5,656.4,85.3,0.4,18.6,0.4,7.9,5.3,48.5
1,Barking and Dagenham,Abbey,14750,3850,10150,750,26.0,69.0,5.0,29.5,...,682.6,208.9,138.1,42.2,1.4,21.9,0.5,6.0,0.8,25.7
2,Barking and Dagenham,Alibon,10600,2700,6800,1050,25.7,64.3,10.0,33.8,...,627.9,201.6,73.6,27.3,0.7,20.6,0.8,3.1,1.0,20.3
3,Barking and Dagenham,Becontree,12700,3200,8350,1100,25.4,65.9,8.7,33.0,...,632.0,207.9,79.9,27.6,1.2,1.9,0.9,2.9,1.6,22.5
4,Barking and Dagenham,Chadwell Heath,10400,2550,6400,1450,24.3,61.5,14.2,36.2,...,613.9,210.5,76.1,24.6,1.3,56.0,0.9,2.3,1.2,25.3

**Q7)** Use `.groupby()` method to create a Series called `population` which contains the `sum` of the values in the `Population - 2015` column for each `Borough` in `wards` DataFrame:

In [20]:
#add your code below
#population =
population = wards.groupby('Borough')['Population - 2015'].sum()
population

Borough
Barking and Dagenham      205400
Barnet                    393350
Bexley                    237050
Brent                     326250
Bromley                   320150
Camden                    230300
City of London              8100
Croydon                   381150
Ealing                    349400
Enfield                   322150
Greenwich                 281700
Hackney                   262850
Hammersmith and Fulham    189800
Haringey                  269100
Harrow                    247550
Havering                  250400
Hillingdon                289450
Hounslow                  263600
Islington                 220850
Kensington and Chelsea    161850
Kingston upon Thames      167300
Lambeth                   320350
Lewisham                  293100
Merton                    206250
Newham                    337900
Redbridge                 292500
Richmond upon Thames      191650
Southwark                 308650
Sutton                    196450
Tower Hamlets             284300
Waltham Forest            271450
Wandsworth                322750
Westminster               230450
Name: Population - 2015, dtype: int64

**Q8)** Use `.groupby()` and `.agg()` methods to create a DataFrame called `cars_stats` which contains the `max`, `min` and `mean` of the `Cars per household - 2011` for each `Borough`in `wards` DataFrame:

In [21]:
#add your code below
cars_stats = wards.groupby('Borough')['Cars per household - 2011'].agg(['max','min','mean'])
cars_stats

                        max  min      mean
Borough
Barking and Dagenham    1.1  0.5  0.811765
Barnet                  1.3  0.8  1.071429
Bexley                  1.4  0.8  1.185714
Brent                   1.4  0.4  0.842857
Bromley                 1.7  0.6  1.218182
Camden                  0.8  0.2  0.472222
City of London          0.4  0.4  0.400000
Croydon                 1.5  0.6  0.995833
Ealing                  1.3  0.7  0.921739
Enfield                 1.3  0.6  1.004762
Greenwich               1.1  0.5  0.788235
Hackney                 0.5  0.3  0.410526
Hammersmith and Fulham  0.9  0.4  0.556250
Haringey                1.0  0.4  0.615789
Harrow                  1.5  0.8  1.204762
Havering                1.6  0.9  1.227778
Hillingdon              1.6  1.0  1.231818
Hounslow                1.3  0.7  1.000000
Islington               0.5  0.3  0.412500
Kensington and Chelsea  0.8  0.4  0.566667
Kingston upon Thames    1.4  0.8  1.131250
Lambeth                 0.8  0.4  0.523810
Lewisham                0.9  0.4  0.666667
Merton                  1.4  0.7  0.940000
Newham                  0.7  0.4  0.610000
Redbridge               1.4  0.7  1.080952
Richmond upon Thames    1.2  0.9  1.061111
Southwark               1.0  0.4  0.528571
Sutton                  1.5  0.8  1.177778
Tower Hamlets           0.6  0.3  0.411765
Waltham Forest          1.3  0.5  0.795000
Wandsworth              1.0  0.4  0.690000
Westminster             0.9  0.3  0.475000

You have been given the below code that will update `cars_stats` so that `mean` is rounded to one decimal place:

In [22]:
cars_stats['mean'] = cars_stats['mean'].round(1)
cars_stats.head(3)

                      max  min  mean
Borough
Barking and Dagenham  1.1  0.5   0.8
Barnet                1.3  0.8   1.1
Bexley                1.4  0.8   1.2

You have been given the below code. The following DataFrame called `transport` which contains the columns `['Borough', 'Ward', 'Average Public Transport Accessibility score - 2014', '% travel by bicycle to work - 2011']` from `wards`:

In [23]:
transport = wards[['Borough', 
                   'Ward', 
                   'Average Public Transport Accessibility score - 2014', 
                   '% travel by bicycle to work - 2011']]

transport.head()

,Borough,Ward,Average Public Transport Accessibility score - 2014,% travel by bicycle to work - 2011
0,City of London,City of London,7.9,5.3
1,Barking and Dagenham,Abbey,6.0,0.8
2,Barking and Dagenham,Alibon,3.1,1.0
3,Barking and Dagenham,Becontree,2.9,1.6
4,Barking and Dagenham,Chadwell Heath,2.3,1.2

**Q9)** Merge the columns from `cars_stats` into `transport`, such that:

- the number of rows in `transport` remains the same
- three new columns are added (`max`, `min`, `mean`)
- the values in each of these columns for all wards in a given `Borough` are the same

In [24]:
#add your code below

# Then merge
transport = transport.merge(cars_stats, how='left', on='Borough')

transport

,Borough,Ward,Average Public Transport Accessibility score - 2014,% travel by bicycle to work - 2011,max,min,mean
0,City of London,City of London,7.9,5.3,0.4,0.4,0.4
1,Barking and Dagenham,Abbey,6.0,0.8,1.1,0.5,0.8
2,Barking and Dagenham,Alibon,3.1,1.0,1.1,0.5,0.8
3,Barking and Dagenham,Becontree,2.9,1.6,1.1,0.5,0.8
4,Barking and Dagenham,Chadwell Heath,2.3,1.2,1.1,0.5,0.8
...,...,...,...,...,...,...,...
620,Westminster,Tachbrook,6.6,5.9,0.9,0.3,0.5
621,Westminster,Vincent Square,6.9,4.3,0.9,0.3,0.5
622,Westminster,Warwick,7.2,5.9,0.9,0.3,0.5
623,Westminster,Westbourne,4.9,5.1,0.9,0.3,0.5
624,Westminster,West End,8.0,3.4,0.9,0.3,0.5

**Q10)** Order the values in `transport` DataFrame using `.sort_values()` method with `ascending=False` parameter, so the `Borough` with the Highest average cars per household  end up at the top:

In [25]:
#add your code below
transport.sort_values('mean',ascending=False,inplace=True)