# Food Health Analysis

KATE expects your code to define variables with specific names that correspond to certain things we are interested in.

KATE will run your notebook from top to bottom and check the latest value of those variables, so make sure you don't overwrite them.

* Remember to uncomment the line assigning the variable to your answer and don't change the variable or function names.
* Use copies of the original or previous DataFrames to make sure you do not overwrite them by mistake.

You will find instructions below about how to define each variable.

Once you're happy with your code, upload your notebook to KATE to check your feedback.

# ☑️ How to complete and submit
Each exercise will look something like this:

```python
example_query = """
SELECT *
FROM sample
"""
#example_result = pd.read_sql(example_query, conn)
#example_result
```

In each exercise you will need to define a query variable by writing the SQL code that you think will solve the problem. SQL code should be enclosed in three double or single quotes.

Once you have your query, uncomment the last two code lines, this will execute it and load the resulting data into a dataframe.

Nothing else needs to be changed in the last code lines besides uncommenting it. 

After running this you will be free to inspect the result produced to see whether it's what you'd expect as the result. KATE will look for variables with the names defined in this notebook, so it is important not to rename the variables defined in this notebook.

Once you've completed the exercises upload this notebook to **KATE** to get feedback. You can also upload the notebook when you only have parts of it completed - if you do so, make sure you do not uncomment the `pd.read_sql` lines for which you don't have a query yet.

Refer to the instructions on **KATE** for more details on the dataset.

# ☑️ Setting up the database connection

Run the following code cell to import `pandas` and `sqlite3` libraries and create the connection to the `sfscores.sqlite` database.

**Do not change this code!** The `conn` variable will be used throughout the notebook to query the database.

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data/sfscores.sqlite')

# ☑️ Introduction to the Food Health dataset

This dataset has been taken from an open data platform (found __[here](https://data.sfgov.org/)__) hosted by the city of San Francisco. It is an sqlite file which is a database created using SQLite. SQLite is a lightweight verion of SQL which features similar syntax to the vast majority of SQL flavours. It provides a fast way of accessing databases and storing databases locally. 

The data includes restaurant scores produced by the San Francisco health department up to and including the year 2016. These scores are generated by a health inspector who bases them upon the violations observed, these violations fall into three categories: High risk, Moderate risk or Low risk. 

The database itself consists of three tables: 

* _**businesses**_: information relating to restaurant businesses such as the owner and location
* _**inspections**_: information about individual inspection events
* _**violations**_: information about violation events

Run the following code cell to show all the tables in the `sfscores.sqlite` database:

In [2]:
query = """
SELECT name 
FROM sqlite_master 
WHERE type='table';
"""
df = pd.read_sql_query(query, conn)
df

          name
0   businesses
1   violations
2  inspections

Referencing these tables and their respective columns will be useful in answering the following questions. Run the following code to show column names and data types within each table:

In [3]:
for table in ['businesses','violations','inspections']:
    
    query = f"""
    PRAGMA table_info({table});
    """
    df = pd.read_sql_query(query, conn)
    print(df[['name','type']])
    print('='*40)

                    name         type
0            business_id      INTEGER
1                   name  VARCHAR(64)
2                address  VARCHAR(50)
3                   city  VARCHAR(23)
4            postal_code   VARCHAR(9)
5               latitude        FLOAT
6              longitude        FLOAT
7           phone_number       BIGINT
8                TaxCode   VARCHAR(4)
9   business_certificate      INTEGER
10      application_date         DATE
11            owner_name  VARCHAR(99)
12         owner_address  VARCHAR(74)
13            owner_city  VARCHAR(22)
14           owner_state  VARCHAR(14)
15             owner_zip  VARCHAR(15)
========================================
              name     type
0      business_id     TEXT
1             date  INTEGER
2  ViolationTypeID     TEXT
3    risk_category     TEXT
4      description     TEXT
========================================
          name          type
0  business_id          TEXT
1        Score       INTEGER
2         date       INTEGER
3         type  VARCHAR (33)
========================================

# ☑️ Queries

## Part 1: Essentials

**1. Write a SQL query that finds the number of `business_id`s in the `businesses` table**

- Consider using SQL `COUNT()` function

See below code syntax for some guidance:
```SQL
SELECT COUNT(column_name)
FROM businesses;
```

In [4]:
#add your code below
number_of_businesses_query = """

SELECT COUNT(business_id)
FROM businesses;

"""
number_of_businesses_result = pd.read_sql(number_of_businesses_query, conn)
number_of_businesses_result

   COUNT(business_id)
0                7616

**2. Write a SQL query that finds out how many unique business `name`'s are registered with the Food Health Department (i.e. all unique businesses in the `businesses` table) and name the column as `unique restaurant name count`.**

- Consider using DISTINCT() function to extract unique values and use COUNT() function to calculate the number of unique values in `name` column

See below code syntax for some guidance:
```SQL
SELECT COUNT(DISTINCT(column_name)) AS <alias>
FROM businesses;
```

In [5]:
#add your code below
unique_business_names_query = """

SELECT COUNT(DISTINCT(name)) AS "unique restaurant name count"
FROM businesses;

"""
unique_business_names_result = pd.read_sql(unique_business_names_query, conn)
unique_business_names_result

   unique restaurant name count
0                          7057

**3. Write a SQL query that finds out what is the earliest and latest `date` a health investigation is recorded in this database, you will find this information in the `inspections` table. Name these columns `earliest date` and `latest date`.**

- Consider using MIN() and MAX() functions on `date` column

See below code syntax for some guidance:
```SQL
SELECT MIN(column_name) AS <alias>, MAX(column_name) AS <alias>
FROM inspections;
```

In [6]:
#add your code below
earliest_and_latest_investigation_query = """

SELECT MIN(date) AS "earliest date", MAX(date) AS "latest date"
FROM inspections;

"""
earliest_and_latest_investigation_result = pd.read_sql(earliest_and_latest_investigation_query, conn)
earliest_and_latest_investigation_result

   earliest date  latest date
0       20131007     20161215

**4. How many `businesses` are there in the database where their owners live in the same area (postal code/zip code) as the business is located?**

- Consider using SQL `COUNT(*)` function
- Consider using `postal_code = owner_zip` as the filtering criteria

See below code syntax for some guidance:
```SQL
SELECT COUNT(*)
FROM businesses
WHERE <condition>;
```

In [7]:
#add your code below
businesses_with_owners_nearby_query = """

SELECT COUNT(*) AS businesses_with_owners_nearby
FROM businesses
WHERE postal_code = owner_zip;

"""
businesses_with_owners_nearby_result = pd.read_sql(businesses_with_owners_nearby_query, conn)
businesses_with_owners_nearby_result

   businesses_with_owners_nearby
0                           4052

**5. Out of those businesses, how many of them has a registered business certificate?**

- Consider using SQL `COUNT(*)` function
- Consider using `postal_code = owner_zip` as one of the filtering criteria
- Also make use of SQL `NOT NULL` while specifying criteria for `business_certificate` column

See below code syntax for some guidance:
```SQL
SELECT COUNT(*)
FROM businesses
WHERE <condition1> AND <condition2>;
```

In [8]:
#add your code below
businesses_with_registered_certificate_query = """

SELECT COUNT(*) 
FROM businesses
WHERE postal_code = owner_zip AND business_certificate IS NOT NULL;

"""
businesses_with_registered_certificate_result = pd.read_sql(businesses_with_registered_certificate_query, conn)
businesses_with_registered_certificate_result

   COUNT(*)
0      3373

## Part 2: Groupby

**6. Find out the distribution of the risk exposure of all the `violations` reported in the database (i.e how many low, moderate and high risk violations are recorded). The first column of the result should be `risk_category` and the second column the count which should be called as `frequency`.**

- Consider using SQL `COUNT(*)` function
- Grouping the data by the `risk_category` column will be helpful

See below code syntax for some guidance:
```SQL
SELECT column_name, COUNT(*) AS frequency
FROM violations
GROUP BY <column_name>;
```

In [9]:
#add your code below
distribution_of_risk_exposure_query = """

SELECT risk_category, COUNT(*) AS frequency
FROM violations
GROUP BY risk_category;

"""
distribution_of_risk_exposure_result = pd.read_sql(distribution_of_risk_exposure_query, conn)
distribution_of_risk_exposure_result

   risk_category  frequency
0      High Risk       5608
1       Low Risk      20996
2  Moderate Risk      14131

**7. Find out the distribution of the risk exposure of all the violations reported in the database that are *water related*. Sort them by frequency (count) from high to low.**

- Consider using SQL `COUNT(*)` function
- To specify the criteria, you may want to use `LIKE` with the `WHERE` keyword
- Consider using `risk_category` column to group the data
- Additionally, sorting the data in descending order could be achieved by using `ORDER BY` keyword

See below code syntax for some guidance:
```SQL
SELECT column_name, COUNT(*) AS frequency
FROM violations
WHERE <condition>
GROUP BY <column_name>
ORDER BY <column_name> DESC;
```

In [10]:
#add your code below
distribution_of_water_risk_exposure_query = """
SELECT risk_category, COUNT(*) AS frequency
FROM violations
WHERE description LIKE '%water%'
GROUP BY risk_category
ORDER BY frequency DESC;
"""

distribution_of_water_risk_exposure_result = pd.read_sql(distribution_of_water_risk_exposure_query, conn)
distribution_of_water_risk_exposure_result

   risk_category  frequency
0  Moderate Risk        630
1      High Risk        237

**8. What types of `inspections` do the authorities conduct and how often do they occur in general. Calculate the distribution of different types of inspections with their frequency (type, frequency) based on inspections records. Sort them in ascending order based on frequency.**

- Consider using SQL `COUNT(*)` function
- Consider using `type` column to group the data
- Additionally, sorting the data in ascending order could be achieved by using `ORDER BY` keyword

See below code syntax for some guidance:
```SQL
SELECT column_name, COUNT(*) AS frequency
FROM inspections
GROUP BY <column_name>
ORDER BY <column_name> ASC;
```

In [11]:
#add your code below
inspection_type_and_frequency_query = """

SELECT type, COUNT(*) AS frequency
FROM inspections
GROUP BY type
ORDER BY frequency ASC;

"""
inspection_type_and_frequency_result = pd.read_sql(inspection_type_and_frequency_query, conn)
inspection_type_and_frequency_result

                                 type  frequency
0          Multi-agency Investigation          1
1   Administrative or Document Review          3
2                       Special Event          7
3                 Routine - Scheduled         74
4     Foodborne Illness Investigation         80
5     Complaint Reinspection/Followup        138
6               Structural Inspection        170
7           Non-inspection site visit        814
8                           Complaint       1625
9                    New Construction       1737
10                      New Ownership       1843
11              Reinspection/Followup       5283
12              Routine - Unscheduled      15568

**9. What is the average score given to restaurants based on the type of inspection? Based on the results, identify the types of inspections that are not scored (NULL) and remove those categories from the resultset. The 'average_score' should be rounded to one decimal. Sort the results in ascending order based on the average score. Hint: use the function `ROUND(AVG(score), 1)`**

- Consider using SQL `AVG()` and `ROUND()` functions
- Also make use of SQL `NOT NULL` while specifying criteria for `Score` column
- Consider using `type` column to group the data
- Additionally, sorting the data in descending order could be achieved by using `ORDER BY` keyword

See below code syntax for some guidance:
```SQL
SELECT column_name, ROUND(AVG(<column_name>)) AS <alias>
FROM inspections
WHERE <condition>
GROUP BY <column_name>
ORDER BY <column_name> ASC;
```

In [12]:
#add your code below
average_score_per_inspection_type_query = """

SELECT 
    type, 
    ROUND(AVG(score), 1) AS average_score
FROM inspections
WHERE score IS NOT NULL
GROUP BY type
ORDER BY average_score ASC;


"""
average_score_per_inspection_type_result = pd.read_sql(average_score_per_inspection_type_query, conn)
average_score_per_inspection_type_result

                    type  average_score
0  Reinspection/Followup           85.0
1  Routine - Unscheduled           91.2
2          New Ownership          100.0

**10. Find the restaurant owners (owner_name) that own one or multiple restaurants in the city with the number of restaurants (num_restaurants) they own. Find the 10 owners who own the most restaurants and sort them by the number of restaurants they own in decreasing order.**


- Consider using SQL `COUNT()` function
- Consider using `owner_name` column to group the data
- Additionally, sorting the data in descending order could be achieved by using `ORDER BY` keyword
- Use `LIMIT` to restrict the results to 10 rows

See below code syntax for some guidance:
```SQL
SELECT column_name, COUNT(<column_name>) AS <alias>
FROM businesses
GROUP BY <column_name>
ORDER BY <column_name> DESC
LIMIT <number_of_rows>;
```

In [13]:
#add your code below
owners_with_restaurant_numbers_query = """

SELECT 
    owner_name, 
    COUNT(*) AS num_restaurants
FROM businesses
GROUP BY owner_name
ORDER BY num_restaurants DESC
LIMIT 10;


"""
owners_with_restaurant_numbers_result = pd.read_sql(owners_with_restaurant_numbers_query, conn)
owners_with_restaurant_numbers_result

                                         owner_name  num_restaurants
0                           VOLUME SERVICES AMERICA               94
1  Department of Children, Youth and their Families               64
2                                             SFUSD               44
3                             Volume Services, Inc.               41
4                       Children's Empowerment Inc.               37
5                      SAN FRANCISCO UNIFIED SCHOOL               34
6                                      WALGREEN CO.               17
7                                       Walgreen Co               15
8                         SMG Food and Beverage LLC               14
9                              STARBUCKS COFFEE CO.               13

## Part 3: Subqueries and joins

**11. From the businesses table, find all owners that own 5 or more restaurants. Then  find the 10 most popular locations for  restaurants (using postal_code) amongst the owners who have 5 restaurants or more. The final result should return the 10 most popular areas  (postal_code) and the frequency with which they appear in our group of owners who own five restaurants or more. The result should have two columns (postal_code and frequency) and should be presented in descending order of frequency.**

Please note you have been provided with the code for this question to carry out the necessary data manipulation and reporting work. Simply run the code cell to produce the desired results.

In [14]:
most_popular_post_codes_query = """
SELECT postal_code, COUNT(*) AS frequency
FROM businesses
WHERE owner_name IN (
SELECT DISTINCT(owner_name)
FROM (SELECT owner_name, COUNT(business_id) AS num_restaurants
    FROM businesses
    GROUP BY owner_name
    ORDER BY num_restaurants DESC) AS restaurant_owners
WHERE restaurant_owners.num_restaurants >= 5)
GROUP BY postal_code
ORDER BY frequency DESC
LIMIT 10;
"""

most_popular_post_codes_result = pd.read_sql(most_popular_post_codes_query, conn)
most_popular_post_codes_result

  postal_code  frequency
0       94107        179
1       94103         67
2       94102         56
3       94110         32
4       94112         30
5       94104         28
6       94124         27
7       94105         23
8       94133         22
9       94111         21

**12. Now it might be interesting to look at some statistics. For all the restaurants in the "94103" post code let's calculate the minimum score (as "min_score"), average score (as "avg_score") and maximum score (as "max_score"). The average score should be rounded to one decimal and you should only consider restaurants that have undergone inspection (so the score is NOT NULL).**

- It is recommended to utilize SQL functions such as `MIN()`, `AVG()`, `ROUND()`, and `MAX()`
- Ensure to include SQL `NOT NULL` when specifying criteria for the `Score` column, and also consider filtering by `postal_code`=`94103`
- Additionally, an `INNER JOIN` can be used to merge the `businesses` and `inspections` tables based on the common field `business_id`

See below code syntax for some guidance:
```SQL
SELECT <column_names>
FROM <table1>
INNER JOIN <table2>
ON table1.column_name = table2.column_name
WHERE <condition1> AND <condition2>;
```

In [15]:
#add your code below
min_avg_max_score_query = """

SELECT 
    MIN(score) AS min_score,
    ROUND(AVG(score), 1) AS avg_score,
    MAX(score) AS max_score
FROM businesses
INNER JOIN inspections
ON businesses.business_id = inspections.business_id
WHERE inspections.score IS NOT NULL
  AND businesses.postal_code = '94103';


"""
min_avg_max_score_result = pd.read_sql(min_avg_max_score_query, conn)
min_avg_max_score_result

   min_score  avg_score  max_score
0         54       90.2        100

**13. Now we can get a bit more serious and look at how many times restaurants in the "94103" post code have committed health violations. We can then group them based on their risk category so we know which restaurants to avoid. The output should have two columns (risk_category, frequency) and be sorted in descending order by frequency**

- Consider using SQL `COUNT(*)` function
- Additionally, an `INNER JOIN` can be used to merge the `businesses` and `violations` tables based on the common field `business_id`
- Consider filtering by `postal_code`=`94103`


See below code syntax for some guidance:
```SQL
SELECT <column_names>
FROM <table1>
INNER JOIN <table2>
ON table1.column_name = table2.column_name
WHERE <condition>
GROUP BY <column_name>
ORDER BY <column_name> DESC;
```

In [16]:
#add your code below
market_street_health_violations_query = """

SELECT 
    violations.risk_category, 
    COUNT(*) AS frequency
FROM businesses
INNER JOIN violations
ON businesses.business_id = violations.business_id
WHERE businesses.postal_code = '94103'
GROUP BY violations.risk_category
ORDER BY frequency DESC;


"""
market_street_health_violations_result = pd.read_sql(market_street_health_violations_query, conn)
market_street_health_violations_result

   risk_category  frequency
0       Low Risk       1746
1  Moderate Risk       1229
2      High Risk        520