**Following guidelines set expectations for participant behaviour during workshop activities. They also ensure that the class environment is welcoming, inclusive, and respectful.**
- Where a discussion is taking place, allow everyone a chance to speak
- Listen respectfully, without interrupting and with an open mind to understanding others’ views
- Be professional and productive, and always share your ideas, your opinion matters, we all can learn something from each other
- Personal information that comes up in the conversation should be kept confidential
- Avoid inflammatory language
- Avoid assumptions about any member of the class or generalisations about social groups

**You have now joined a group of fellow analysts in a workshop:**
#### Outcomes:

- To be able to answer the questions to test your knowledge of SQL queries


#### Note:
- We understand learners will progress at their own speed
- Tutors will be on hand to answer questions

# ☑️ SQL Statements: Column Operations

- Complete the following questions
- Make sure you run the following code cells before you attempt any of the questions
- We will work with `flights.db` database through this workbook

First, import pandas and sqlite3 libraries and create the connection to the `flights.db` database, located in the `data` folder:

In [1]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('data/flights.db')

A database might have multiple tables. It's a good idea to do an initial exploration of the database by first querying the `sqlite_master` table to see what tables are in the database.

Run the following code cell to show all the tables in the `flights.db` database:

In [2]:
query = """
SELECT name 
FROM sqlite_master 
WHERE type = 'table';
"""
df = pd.read_sql_query(query, conn)
df

       name
0  airports
1  airlines
2    routes

Run the following code cell to show the schema for each table in `flights.db` database:

In [3]:
for table in ['airports','airlines','routes']:
    
    query = f"""
    SELECT sql 
    FROM sqlite_master 
    WHERE name = '{table}';
    """
    
    df = pd.read_sql_query(query, conn)
    print(''.join(df.values[0, 0]))

CREATE TABLE airports (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [city] TEXT,
  [country] TEXT,
  [code] TEXT,
  [icao] TEXT,
  [latitude] TEXT,
  [longitude] TEXT,
  [altitude] TEXT,
  [offset] TEXT,
  [dst] TEXT,
  [timezone] TEXT
)
CREATE TABLE airlines (
[index] INTEGER,
  [id] TEXT,
  [name] TEXT,
  [alias] TEXT,
  [iata] TEXT,
  [icao] TEXT,
  [callsign] TEXT,
  [country] TEXT,
  [active] TEXT
)
CREATE TABLE routes (
[index] INTEGER,
  [airline] TEXT,
  [airline_id] TEXT,
  [source] TEXT,
  [source_id] TEXT,
  [dest] TEXT,
  [dest_id] TEXT,
  [codeshare] TEXT,
  [stops] TEXT,
  [equipment] TEXT
)

# ☑️ SQL Statements

**Q1)** Refer to the `airlines` table. How many airlines start with a number between `0` and `9`?
- You can use `COUNT(*)` to count the number of rows returned

Please note you have been provided with the code for this question to carry out the necessary analysis work. Simply run the code cell to produce the desired results.

In [4]:
query = """
SELECT COUNT(*) 
FROM airlines 
WHERE SUBSTR(name, 1, 1) BETWEEN '0' AND '9';
"""
df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0        16

**Q2)** Refer to the `country` column in `airlines` table. How many countries have at least one airline?

- Consider `IS NOT NULL` keyword to filter out any NULL values in `country` column

- Use DISTINCT() function to extract distinct values and use COUNT() function to calculate the number of distinct values in `country` column

See below code syntax for some guidance:
```SQL
SELECT COUNT(DISTINCT(column_name))
FROM airlines 
WHERE <column_name> IS NOT NULL;
```

In [5]:
#add your code below
query = """
SELECT COUNT(DISTINCT(country))
FROM airlines 
WHERE country IS NOT NULL;
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(DISTINCT(country))
0                       276

**Q3)** Refer to the `altitude` column in the `airports` table. Find the **five** airports with the highest `altitude`.  

Please note that the `altitude` column is stored as a **text** data type, which prevents the `ORDER BY` operation from being performed correctly.

- Refer to the `ORDER BY` keyword, and use the **CAST()** function to convert the `altitude` column to the `INT` data type.  
  - **Example**: `CAST(altitude AS INT)`  
- The values should now be ordered correctly.

See below code syntax for some guidance:

```SQL
SELECT name, country, altitude
FROM airports
ORDER BY CAST(<column_name>) DESC
LIMIT 5;
```

In [6]:
#add your code below
query = """

SELECT name, country, altitude
FROM airports
ORDER BY CAST(altitude AS FLOAT) DESC
LIMIT 5;
"""

df = pd.read_sql_query(query, conn)
df

                   name country altitude
0       Yading Daocheng   China    14472
1  Qamdo Bangda Airport   China    14219
2      Kangding Airport   China    14042
3                 Gunsa   China    13780
4             Irkutsk-2  Russia    13411

**Q4)** Refer to the `name` and `altitude` columns in `airports` table. Further filter your data to get all airports from `United Kingdom`.

See below code syntax for some guidance:
```SQL
SELECT name, altitude
FROM airports
WHERE country='United Kingdom';
```
Now use CASE() statement to create a new calculated column called `altitude2` to reflect below conditions and results:
- Return "Low" if altitude lower than 100m
- Otherwise return "Medium" if altitude lower than 500m
- Otherwise return "High"

See below code syntax for some guidance:
```SQL
CASE
    WHEN CAST(altitude AS INT) < 100 THEN 'Low'
    WHEN CAST(altitude AS INT) < 500 THEN 'Medium'
    ELSE 'High'
END AS altitude2
```

In [7]:
#add your code below
query = """
SELECT name, altitude,
CASE
    WHEN CAST(altitude AS INT) < 100 THEN 'Low'
    WHEN CAST(altitude AS INT) < 500 THEN 'Medium'
    ELSE 'High'
END AS altitude2
FROM airports
WHERE country='United Kingdom';

"""

df = pd.read_sql_query(query, conn)
df

                       name altitude altitude2
0              Belfast Intl      268    Medium
1                 St Angelo      155    Medium
2              Belfast City       15       Low
3             City of Derry       22       Low
4                Birmingham      327    Medium
..                      ...      ...       ...
205    Queen Street Station       50       Low
206  Waterloo International       10       Low
207         Central Station       25       Low
208          Euston Station       89       Low
209  Waterloo International       10       Low

[210 rows x 3 columns]

**Q5)** Refer to the `airports` table. Now, calculate the total number of airports.

Please note you have been provided with the code for this question to carry out the necessary analysis work. Simply run the code cell to produce the desired results.

In [8]:
query = """
SELECT COUNT(*)
FROM airports;
"""

df = pd.read_sql_query(query, conn)
df

   COUNT(*)
0      8107

# ☑️ Group Metrics

**Q6)** Refer to the `city` column in `airports` table to find the number of airports per city.

- Consider `GROUP BY` keyword to group data by `city` column

See below code syntax for some guidance:
```SQL
SELECT column_name, COUNT(*)
FROM airports
GROUP BY <column_name>;
```

In [9]:
#add your code below
query = """
SELECT city, COUNT(*)
FROM airports
GROUP BY city;
"""

df = pd.read_sql_query(query, conn)
df.head(5)

               city  COUNT(*)
0    108 Mile Ranch         1
1               Aaa         1
2            Aachen         2
3           Aalborg         1
4  Aalen-heidenheim         1